[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Database setup
[[plugins]]
  package = "netlify-plugin-prisma-provider"

[context.production.environment]
  NODE_ENV = "production"